# Based On: https://github.com/marketplace/actions/build-and-push-docker-images

name: Docker build and push to docker hub

on:
  push:
    branches:
      - main  # Trigger the workflow on push or pull request to the main branch

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.7
        
      - name: Set tag by date
        id: tagbydate
        run: echo "tag=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_OUTPUT
    
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
          
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            ${{ vars.DOCKER_TAG }}:latest
            ${{ vars.DOCKER_TAG }}:${{ steps.tagbydate.outputs.tag }}

  deploy:
    runs-on: ubuntu-latest
    needs: docker
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ vars.DEPLOY_HOST }}
          username: ${{ vars.DEPLOY_USERNAME }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          port: ${{ vars.DEPLOY_PORT }}
          script: |
            ${{ vars.DEPLOY_UPDATE_SCRIPT }} 
